# Настройки запуска линтера
run:
  tests: true
  timeout: 5m
  skip-dirs:
    - vendor
  build-tags:
    - !cgo

# Настройки отдельных линтеров
linters-settings:
  funlen:
    lines: 150
    statements: 80
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  lll:
    line-length: 140
  gofmt:
    simplify: true
  gosimple:
    go: "1.21"
  staticcheck:
    go: "1.21"
  revive:
    rules:
      - name: package-comments
        disabled: false
      - name: exported
        disabled: false

# Настройки включения/отключения линтеров
linters:
  disable-all: true
  enable:
    - gofmt
    - gofumpt
    - govet
    - gosimple
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gocritic
    - gosec
    - stylecheck
    - whitespace
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - funlen
        - goconst
    - path: ui/
      linters:
        - gosec
        - gocritic
    - path: main.go
      linters:
        - gosec
  max-same-issues: 50
  exclude-use-default: false