name: Linting

# Запуск при пуше в любую ветку.
on:
  push:
    branches:
      - '**'

jobs:

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    
    steps:
      # Установка Go версии 1.21.
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      # Получение исходного кода из репозитория.  
      - name: Check out code
        uses: actions/checkout@v4
      
      # Установка зависимостей.
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xorg-dev libgl1-mesa-dev

      - name: Install Go dependencies
        run: go mod download

      # Запуск линтеров.
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          args: --timeout=5m
          skip-pkg-cache: true
          skip-build-cache: true