name: Testing

# Запуск при пуше в любую ветку.
on:
  push:
    branches:
      - '**'

jobs:

  tests:
    runs-on: ubuntu-latest
    
    steps:
      # Установка Go версии 1.21.
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      # Получение исходного кода из репозитория.  
      - name: Check out code
        uses: actions/checkout@v3

      # Установка системных зависимостей.
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xorg-dev libgl1-mesa-dev

      # Установка зависимостей.
      - name: Install Dependencies
        run: go mod tidy

      # Запуск юнит-тестов.
      - name: Run tests
        run: go test -race -v ./...